//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MatType { get; set; }
        public string Picture { get; set; }
        public string Price { get; set; }
        public string Count { get; set; }
        public string MinCount { get; set; }
        public string BoxCount { get; set; }
        public string metters { get; set; }
    }
}
